-- Table structures for Keep Track!

CREATE TABLE ACCOUNT 
	(ACCOUNT_ID VARCHAR(200) NOT NULL, 
	EMAIL VARCHAR(200) NOT NULL, 
	PASSWORD VARCHAR(200) NOT NULL, 
	ACCOUNT_TYPE CHAR(4) NOT NULL, 
	FIRST_NAME VARCHAR(200) NOT NULL, 
	LAST_NAME VARCHAR(200) NOT NULL, 
	PHONE CHAR(10), PRIMARY KEY (ACCOUNT_ID));

CREATE TABLE EVENT 
	(EVENT_ID VARCHAR(200) NOT NULL, 
	CREATOR_ID VARCHAR(200) NOT NULL, 
	OWNER_ID VARCHAR(200) NOT NULL, 
	TITLE VARCHAR(200) NOT NULL, 
	DESCRIPTION VARCHAR(4000) NOT NULL, 
	EVENT_DATE TIMESTAMP NOT NULL, 
	STATUS CHAR(1), 
	PRIMARY KEY (EVENT_ID));

CREATE TABLE EVENT_REMINDER 
	(EVENT_ID VARCHAR(200) NOT NULL, 
	ACCOUNT_ID VARCHAR(200) NOT NULL, 
	REMINDER_DATE TIMESTAMP NOT NULL, 
	SENT_FLAG CHAR(1) NOT NULL, 
	PRIMARY KEY (EVENT_ID, 
	ACCOUNT_ID, REMINDER_DATE));
